3rdparty_licenses/LICENSE.BSD-3.arm
Makefile
README.md
src/main.c
src/memory.c
src/memory.h
src/memory_asm.S
src/utils.h

This PR adds basic MMU support to m1n1.
Still missing:
- Tests on real hardware. This has only been verified inside qemu so far
- Proxy calls to disable the MMU before e.g. jumping to Linux

MMU support

---

proxyclient/addrdump.py
proxyclient/aic_test.py
proxyclient/asm.py
proxyclient/chainload.py
proxyclient/chickens.py
proxyclient/linux.py
proxyclient/malloc.py
proxyclient/memdump.py
proxyclient/proxy.py
proxyclient/shell.py

`Signed-off-by: Witold Baryluk <witold.baryluk@gmail.com>`

Fix #! and exec bits for scripts

---

proxyclient/proxy.py

Use miniterm from pyserial for tty passthrough mode
Signed-off-by: Khoa Hoang <admin@khoahoang.com>

proxyclient: add input support for tty mode

---

proxyclient/chainload.py
proxyclient/malloc.py
proxyclient/utils.py

chainload.py: transparently compress payload to improve loading time

---

proxyclient/asm.py

proxyclient/asm.py: allow to override compiler prefix

---

.github/workflows/main.yml
Makefile

ci: add clang-format check to the CI

---

proxyclient/i2c.py

unfortunately not enough to bring up usb in host mode...

proxyclient/i2c: experiment with the i2c and ti usb chip

---

proxyclient/proxy.py
src/proxy.c
src/proxy.h

looks like i dropped this commit while splitting the DART PR...

proxy: add dart ops

---

proxyclient/linux.py

right now u-boot can bring up the PCIe bus such that Linux only requires
a very minimal driver. this new --uboot flag for linux.py allows to load
u-boot before the Linux kernel to make use of this.
This requires a small hack to inject the booti command into the default
u-boot boot environment.

proxy: linux.py: allow to load u-boot before Linux

---

proxyclient/proxy.py
src/uartproxy.c

(based on feedback from previous PR #59 )
This allows disabling checksumming on memory reads, writes, and MMIO traces by setting the `DISABLE_CSUMS` environment variable.
To ensure compatibility, the checksum disabling is only used if both sides agree on using it; this is determined by feature flags that are exchanged during the initial `REQ_NOP` sent by `boostrap_port`:
* The checksum algorithm used for NOP messages is not modified by this feature so feature detection will work in all cases
* If an older version of m1n1 is used, it will ignore the feature flags in the NOP message and return 0 in the reply message, so no features will be enabled.
* If an older version of the proxy is used, it will send in its NOP message; m1n1 will disable all features and return 0 in the reply message.

Add an option to disable checksumming if possible

---

.github/workflows/build.yml

ci: add a m1n1 build CI job

---

proxyclient/dart_dump.py

forgot to add this with the DART stuff. this is useful to e.g. inspect the disp0 dart.

proxy: add dart_dump.py

---

src/kboot.c

Read the MAC addresses from the ADT and store them in
"local-mac-address" properties on the relevant nodes in the FDT.
This relies on appropriate aliases in the provided FDT, which
matches how U-Boot provides MAC addresses on embedded targets.

kboot: Provide MAC addresses in device tree

---

proxyclient/hv/trace_gpio.py
proxyclient/m1n1/hv.py
proxyclient/m1n1/utils.py

Adds a handler for "/arm-io/gpio" as example.

Add support for device specific mmiotrace handlers

---

proxyclient/hv/trace_dcp.py
proxyclient/m1n1/trace/asc.py

Nothing of much substance here, but it significantly improves the signal:noise ratio for trace-dcp ... frame present stuff isn't that interesting by itself, the modesetting stuff is much more so.

Decode some DCP mailbox messages

---

proxyclient/m1n1/hv.py

Also removes unused leftover demonstration code which came obsolete by
tracer scripts. See hv/trace_gpio.py for an example.

m1n1/hv: fix irq trace after "Rework MMIO PT handling & tracing"

---

proxyclient/m1n1/hv.py
proxyclient/m1n1/sysreg.py
src/hv_exc.c
src/uartproxy.h

hv: add single stepping and hardware breakpoint support

---

proxyclient/m1n1/hw/sep.py

proxyclient: sep: add initial code to boot SEPOS

---

README.md

force-pushed to add DCO signoff. if signoff under a pseudonym is not acceptable, please close without merging.

fix typo of "arm-trusted-firmware" in README.md

---

proxyclient/experiments/speaker_amp.py
proxyclient/m1n1/hw/admac.py
proxyclient/m1n1/hw/i2c.py

This is the code from a paste I posted earlier (https://gist.github.com/povik/66f69f539905bcde6f4cacbae1d24ad6) after some additional care.
(I will be happy to add sign offs once it's specified somewhere what those sign offs mean. :) )

Bit of audio

---

proxyclient/m1n1/asm.py
proxyclient/m1n1/find_regs.py
proxyclient/m1n1/fw/dcp/ipc.py
proxyclient/m1n1/hv.py
proxyclient/m1n1/proxy.py
proxyclient/m1n1/proxyutils.py
proxyclient/m1n1/sysreg.py

Little clean-up of unused proxyclient code.
Code used/referenced by commented out sections were taken into account and left behind to be used by it at a later point.
Signed-off-by: TophEvich <84676511+TophEvich@users.noreply.github.com>

proxyclient: removed unused code

---

proxyclient/hv/trace_atc.py

proxyclient: hv: Add simple DWC3/XHCI/ATCPHY tracer

---

proxyclient/m1n1/proxy.py

proxyclient: Expect m1n1 at /dev/ttyACM0

---

proxyclient/m1n1/proxyutils.py

Rework the serial port bootstrap so it works correctly if the target is already
at 1500000 baud.
No baud adjustment is made if the proxy is using the serial-USB interface.
Tested with the Mac-to-Mac serial connection (macvdmtool) and the serial-USB
connection.

bootstrap_port: Improve UART baud setting

---

proxyclient/experiments/speaker_amp.py
proxyclient/m1n1/hw/admac.py
proxyclient/m1n1/hw/i2c.py
proxyclient/m1n1/hw/nco.py
proxyclient/m1n1/hw/sep.py
proxyclient/m1n1/utils.py
proxyclient/tools/dump_pmgr.py

These are some smaller changes that I have accumulated, with the addition of code for driving the NCO on top.

Various audio-related changes

---

src/kboot.c

Read the antenna SKU from the ADT and store it in a
"apple,antenna-sku" property on the relevant node in the FDT.

kboot: Provide antenna SKU in device tree

---

README.md

Could also use the symbol: &copy;

Consistency for (c)

---

Makefile
proxyclient/m1n1/proxy.py
src/asc.c
src/asc.h
src/i2c.c
src/iova.c
src/iova.h
src/nvme.c
src/nvme.h
src/pcie.c
src/pmgr.c
src/pmgr.h
src/proxy.c
src/proxy.h
src/rtkit.c
src/rtkit.h
src/sart.c
src/sart.h
src/usb.c
src/utils.h

the iova.c/h stuff is only very lightly tested. I originally thought I'd need that for NVMe for some reason.
SARTv3 (or anything else that requires the Pro/Max) isn't tested at all.
The NVMe part right now is just a stub that boots the co-processor to verify that the rest works correctly.

ASC, SART, RTKit and NVMe Stub

---

src/display.c

It takes 5 tries to detect my 1920x1080@60 displays (accumulated delay 400ms). 2 seconds selected to have 5 times margin of error and a not too annoying delay when no display is connected.
I hope we can decrease delay after we have seen how long the display detection usually takes.

display: Retry dcp_ib_get_hpd() for up to 2 seconds

---

proxyclient/m1n1/fw/afk/epic.py
src/afk.c

Fix DCP on 11.x FW

---

src/kboot.c

These properties are needed such that U-Boot can enable the
serial port in its early pre-relocation phase.

kboot: Add u-boot,dm-pre-reloc properties

---

proxyclient/experiments/audio_capture.py
proxyclient/experiments/speaker_amp.py
proxyclient/m1n1/hw/admac.py
proxyclient/m1n1/hw/mca.py

Notably this demonstrates audio capture.

New audio bits

---

proxyclient/m1n1/hv.py

We already have breakpoints and symbols, let's make our life easier
by also allowing to break on symbols.

hv.py: Add helper to break on symbols

---

rust/src/dlmalloc.rs

This fixes #168 (`dlmalloc.rs` assumes `realloc` will keep alignment from `posix_memalign`) by falling back to allocating a new chunk with the `GlobalAlloc::alloc()` trait method if resizing in-place fails.
Note that this code is not tested on actual hardware since I do not have an Apple M1 device.
I *have* tested the Rust code on its own (outside of m1n1, see [here](https://github.com/Ferdi265/test-realloc-alignment)) though.
Signed-off-by: Ferdinand Bachmann <theferdi265@gmail.com>

rust: do not assume realloc preserves alignment

---

proxyclient/m1n1/hv.py

preoslog was added in macos 12.3 and seems to contain iBootStage1 log
output. Since macos 12.3 accesses it it has to be copied to after the
guest image.

m1n1.hv: Copy /chosen/memory-map/preoslog if it exists

---

src/kboot.c

kboot: propagate ATC tunables to the FDT

---

proxyclient/m1n1/proxy.py

Signed-off-by: Akihiko Odaki <akihiko.odaki@gmail.com>

proxy: Specify coordinates in fb_fill method

---

proxyclient/m1n1/shell.py

Signed-off-by: Akihiko Odaki <akihiko.odaki@gmail.com>

m1n1.shell: Don't save history if init failed

---

src/kboot.c

To support https://github.com/jannau/linux/tree/asahi-t6002 with the hypervisor.
Marked as draft since the address translation via "ranges" for the second die is missing. This results in disabling devices on both dies if the device is on die 0 and failing to disable devices if the device is on die 1.

kboot: support multi die machines in dt_disable_missing_devs

---

Makefile
proxyclient/experiments/mmio_sweep.py
proxyclient/experiments/speaker_amp.py
proxyclient/m1n1/hw/admac.py
proxyclient/m1n1/hw/mca.py
proxyclient/m1n1/loadobjs.py
proxyclient/m1n1/proxyutils.py
proxyclient/tools/second_proxy.py

Commit stash flushing

---

proxyclient/hv/trace_nvme.py

hv/trace_nvme: Trace rtkit interface and remove hardcoded sart address

---

proxyclient/m1n1/proxy.py

Return the result in setX, clearX and maskX functions.
Signed-off-by: Radovan Blažek <blazra@gmail.com>

proxyclient/m1n1/proxy.py: Add missing returns

---

src/dart.c
src/kboot.c

Linux changes are in https://github.com/jannau/linux/tree/asahi-6.1-rc5-11-dcp-m2

T8112 DCP support

---

proxyclient/hv/trace_z2.py

Add z2 touch panel tracing

---

src/kboot.c

kboot: Copy ACIO tunables and DROM data

---

src/pcie.c

The SD card reader on Macbook Pro 14"/16" and Mac Studio uses yet another property to override the port's "maximum-link-speed" property. Add parsing for "expected-link-speed" and always look in the port's first child for these properties.
Increases the link speed to PCIe 2.0 which is required for the full bandwidth of SDXC UHS-II.

pcie: Add link speed override for SD card reader

---

proxyclient/experiments/ane.py
proxyclient/m1n1/fw/ane.py
proxyclient/m1n1/hw/ane.py

Documentation is WIP, and should be added soon.
Signed-off-by: Eileen Yoon <eyn@gmx.com>

m1n1/ane: Initial commit

---

proxyclient/m1n1/asm.py

m1n1.asm: make it work again on OpenBSD

---

data/makelogo.sh

This just adds the necessary shebang.

makelogo.sh: Add `#!/bin/bash`

---

src/cpu_regs.h
src/hv_exc.c

Cleanup and name some previouly-unnamed registers

---

.packit.yaml

As suggested by @jannau in https://github.com/AsahiLinux/m1n1/pull/271#issuecomment-2663990301

packit: tweak the build targets

---

.github/workflows/build.yml
.github/workflows/main.yml

```diff
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
```
https://github.com/actions/checkout/releases

Upgrade GitHub Actions

---

Dockerfile

upd: buster to bookworm
