src/string.c

this is required to fix the following error when compiling with clang:
```
CC    build/string.o
src/string.c:3:10: error: 'string.h' file not found with <angled> include; use "quotes" instead
^~~~~~~~~~
"string.h"
```

change #include <string.h> to #include "string.h"

---

src/adt.h

adt_getprop_copy is defined as const in src/adt.c but not in src/adt.h

add missing const to src/adt.h

---

proxyclient/proxy.py

While watching the m1n1 bring-up stream I noticed a small copy-paste error in `proxyclient.py`:
The `mask8() .. mask64()` functions still use the `P_CLEAR8 .. P_CLEAR64` opcode and don't pass the address.
This commit fixes that.
Commit is untested since I don't have an M1, but the change is small enough that it most likely works.

proxyclient: fix mask commands accidently sending clear opcode instead

---

src/adt.c
src/adt.h

This commit removes the unnecessary `const` on `adt_getprop_copy()` in both the header and the C file, since `const int` as a return type does not do anything different than just `int`, and the added `const` might be confusing to some.
See also the discussion in #5 "add missing const to src/adt.h".

adt: fix ignored qualifiers in adt_getprop_copy function prototype

---

Makefile

Seems (possibly older) versions of binutils, like 2.31.1 set the ELF arch to 'no machine' when the input format is arch-less, causing a link failure later.

build: fix problem with arch-less data on older GNU binutils

---

src/exception_asm.S

This commit removes the leftover and unused `push_hi_regs` symbol, since only `_exc_entry` is actually used.

exceptions: remove unused push_hi_regs symbol, make _exc_entry a function

---

src/types.h

This PR fixes a warning found by compiling m1n1 with clang.
- `src/types.h` redefines `NULL`, which is already defined in `<stddef.h>`

types.h: remove redundant definition of NULL (defined in stddef.h)

---

Makefile
m1n1.ld
src/exception.c
src/start.S
src/types.h

@svenpeter42 and I worked on getting m1n1 to compile cleanly with clang, and I think we got something that should work.
This PR enables m1n1 to be built with clang, by adding the `USE_CLANG=1` argument when invoking `make`.
Notable changes:
- the `-mabi=lp64` flag was removed since clang doesn't understand it and `aarch64-linux-gnu-gcc` builds in that mode by default.
- the `-fno-stack-protector` flag was added since clang inserts stack protector guards that produce a linker error otherwise.
- the `-mgeneral-regs-only` flag was added since clang produces code that writes to the `qN` registers otherwise, and m1n1 doesn't save those during interrupts.
- the `-shared` linker flag was removed since LLD doesn't like it being used together with `-pie` and GNU ld behaves the same without it …

Makefile: add support for compiling m1n1 with clang

---

Makefile
src/adt.c
src/adt.h
src/exception.c
src/startup.c
src/types.h
src/utils.c
src/utils.h

Signedness: 
- `adt.c`: Replaces `int` usage to `uint32_t` for property size (`lenp`) and `size_t` for property name length (`len`).  
This change differs from the API in libfdt but is consistent with the data types of the property and their usage.
- adt.h: Removes `adt_getprop_length` declaration without implementation
Increases compiler warnings to expose some common issues to review:
- Makefile: `Wsign-compare` / `Wunused-parameters` 
-  UNUSED macro to suppress this warning in function parameters that are in ongoing work, debug or subject to API review.
Signed-off-by: Ariel Machado <ariel@fe.up.pt>

Signedness: Replaces int to uint32_t and size_t for unsigned values

---

proxyclient/proxy.py

Proxy.py has a few typos that appear if you try to use debug mode and dump a region of memory. This should fix those.

Fix broken hexdumps in proxy.py

---

src/utils.h

Clang raises 'asm-operand-widths' warnings in inline assembly code when the size of an operand is < 64 bits and the operand width is unspecified.
Warnings are raised in `_msr(reg, val)` macro, i.e. the datatype of the operand may vary. 
In the macro we cast the operand to 64 bits, forcing the use of the right 64-bit register size.
Signed-off-by: Ariel Machado <ariel@fe.up.pt>

utils.h: Fix 'asm-operand-widths' warnings with clang

---

proxyclient/linux.py

Decompression time is negligible compared to the loading over the 1.5mpbs serial interface.

Linux loader xz and bootargs support

---

src/memory.c

I can't remember why I used vmalls12e1is but this leads to
the following bug:
1. Load m1n1 with normal MMU setup
2. Disable all mappings, recompile and chainload to that m1n1
3. Everything will work fine for a while even though it should explode
when enabling the MMU.
This happens becuse there are still stale TLB entries in some cache.

MMU: use alle2 instead of vmalls12e1is to invalidate TLBs

---

proxyclient/proxy.py
src/proxy.c
src/proxy.h
src/utils.h

These functions all perform a store direcly followed by a load.
This is useful to e.g. useful to find busy bits which might
already be cleared a few cycles after a write.

Add writeread functions + proxy ops

---

Dockerfile
README.md
docker-compose.yml

This allows compiling m1n1 on any platform that supports containers / Docker and doesn't require using a separate Linux build machine.
With Docker(-Compose) installed building m1n1 can be done by running: 
```
$ docker-compose build
$ docker-compose run m1n1 make
```

tooling: Add container setup for build environment

---

src/memory.c

Previously all MMIO was mapped twice with different attributes
which may or may not lead to strange behaviour when the same
physical range is accessed from both mappings.
We now have a better idea which ranges require nGnRE and nGnRnE
and can just do it correctly instead.

MMU: correctly map MMIO/PCIe ranges

---

Makefile
proxyclient/proxy.py
src/proxy.c
src/proxy.h
src/tunables.c
src/tunables.h

There are at least two types in the ADT related to USB,
but there's a decent chance that there are even more
required for other devices:
* A simple tunable that applies to a whole device node
and all it's MMIO ranges specified in the "reg" property.
This one seems to just be mask32.
* A slightly more complex tunable that applies to a single
MMIO range specified in the "reg" property. So far I've
only seen 32 bit masks but the format looks like it should
also support 8,16 and 64 bit masks.
Open question: How do we expose proxyclient ops for these? Unlike everything else they take a string as an argument and right now there's no way to easily serialize those.

tunables: add initial version.

---

proxyclient/chainload.py

Last changes to chainload.py broke the EL1 support (--el1).
Here is a quick fix for that.

chainload.py: Fix el1 support

---

proxyclient/hv.py
proxyclient/proxy.py
src/hv.h
src/hv_vuart.c
src/iodev.c
src/iodev.h
src/proxy.c
src/usb.c
src/usb_dwc3.c
src/usb_dwc3.h

Second ACM interface is always announced but will be only used for the virtualized uart. Depends on using the other interface of the same USB device as proxy/hv connection. No support in `proxy/`.
USB device/interface handling is awkward and probably not using the right abstraction.
Read support not implemented.

usb/hv: add second CDC ACM interface for virtualized UART

---

Makefile
src/main.c
src/pcie.c
src/pcie.h

Minimal initialization of the PCIe hardware such that the tunable
can be applied such that they don't have to be passed along in
the devicetree.

pcie: minimal initialization

---

proxyclient/linux.py

commit 35fddd51 broke loading a kernel without explitly specifying
a tty.  Fix this.

proxy: linux.py: fix tty initialization

---

proxyclient/shell.py

* Use the object’s class to find methods to import into the shell namespace rather than the object itself, to avoid invoking properties on the object.
* Prevent importing of members whose name starts with `_` (private methods and Python magic methods).
This removes the following items from the shell namespace (as checked by `dir()`):
```
__class__
__delattr__
__dir__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
_request
```
If I’m not mistaken, they are not actually useful.

Shell: do not access properties on startup

---

src/dart.c

This should allow Linux (and other kernels) to boot and even use the usb-c ports even without a DART driver.
It also restore the DART registers to the state they are left in by iBoot.

Shutdown DART to bypass mode

---

Makefile
proxyclient/adt.py
proxyclient/hv.py
proxyclient/proxy.py
src/hv.h
src/hv_aic.c
src/hv_vm.c
src/proxy.c
src/proxy.h
src/uartproxy.h

Implemented by MMIO tracing of AIC's event register. Proposed by pipcet.
Would be nice if we could hook just the event register at offset 0x2004.

hv: add interrupt tracing

---

src/usb_dwc3.c

usb_dwc3: shutdown the DART as well when shutting down usb

---

proxyclient/tools/reboot.py

An alternative could be adding a command parameter to shell.py but `./tools/shell.py -c 'p.reboot()'` is a little annoying to type

proxy/tools: add reboot.py

---

proxyclient/m1n1/hv.py
src/hv.c
src/proxy.c
src/tps6598x.c
src/tps6598x.h
src/usb.c
src/usb.h

Restore the interrupt masks on transition to the next state. The masks
are not restored on the USB-C port used by the hypervisor. This prevents
an interrupt storm in the guest when the other USB-C port is exposed to
the guest. The tps6598x interrupt line is shared amoung both ports.

usb: disable tps6598x interrupts

---

Makefile
src/cpio.c
src/cpio.h
src/kboot.c
src/kboot.h

We won't be able to bootstrap SEPOS from m1n1 since that process requires us to setup a shared memory region.
Handing this region, which is mapped through a DART, over to the OS would be fragile and prone to errors.
Instead, the booted OS will have to boot SEPOS using the firmware passed by iBoot.

copy sepfw to initrd 

---

proxyclient/tools/linux.py

linux.py: add missing serial import

---

src/uartproxy.c
src/usb.c

without this macOS complains about the USB device that goes missing
once m1n1 hands control to Linux

fix linux boot issues on macOS

---

src/startup.c

Use the right unit. for rgb10x2, this prints "30bpp" instead of "0x1E".
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>

startup: Prettyify video depth dump

---

proxyclient/m1n1/utils.py

This is not a major issue, so please feel free to close without further discussion.
`compact` currently merges ranges without checking they're actually adjacent. For example, this test fails:
```
a = BoolRangeMap()
a.set(range(0, 2))
a.set(range(4, 6))
a.compact()
a.clear(range(3, 5))
expect = [True, True, False, False, False, True, False]
for i,j in enumerate(expect):
assert a[i] == j
```
Also, tracing access to memory (not MMIO) ranges doesn't throw an error, but also fails to work, for this reason. I can provide examples if that would be considered helpful.

proxyclient/m1n1/utils.py: don't compact non-adjacent ranges

---

proxyclient/m1n1/shell.py

The proxyclient/tools/shell.py is broken because the Signature of UartError:
ValueError: no signature found for builtin type <class 'm1n1.proxy.UartError'>
Fixed by just skipping help for those items

Fix Exception when no Signature present

---

src/hv_vuart.c

I believe this fix, or something like it, is necessary to avoid spurious NUL bytes being received over the vUART by the Linux driver.
(Unfortunately, I'm having a hard time testing the vUART right now. I'm using vanilla m1n1 on a machine that has never booted anything but vanilla m1n1 and macOS, and am booting straight from iBoot...)
Anyway, it's a pretty obvious fix :-)

Avoid reporting bytes in the RX buffer when it's empty.

---

proxyclient/hv/trace_dcp.py
proxyclient/m1n1/fw/dcp/ipc.py
proxyclient/m1n1/fw/dcp/manager.py

This isn't enough to set the video mode yet but it gets us further. I
think allocate_memory/map_buf/powerOnDART need real implementations,
otherwise setting a video mode crashes the DCP in an APIODMA interrupt
handler, whatever that is.
Yes, this a blatant attempt at nerdsniping marcan into debugging that.

fw.dcp: Add some stubs needed for modesetting

---

src/iodev.c
src/uart.c
src/usb_dwc3.c

Tiny readability fixes. If you don't want this kind of fix, please let me know, but at least this hunk:
```
-    return read32(UART_BASE + UTRSTAT) & UTRSTAT_RXD;
+    return (read32(UART_BASE + UTRSTAT) & UTRSTAT_RXD) ? 1 : 0;
```
seems important to me to make the code more obviously correct.

Cosmetic fixes, avoid relying on UTRSTAT_RXD == 1

---

src/pcie.c

The macbook pro and macbook air only have a single PCIe port

pcie: Only initialize ports that are actually present

---

src/main.c

Older versions of GCC throw a "initializer element is not contstant"
error.  Fix this.

main: Fix compiler error

---

proxyclient/experiments/smc.py
proxyclient/m1n1/fw/smc.py

Add a basic SMC client and a script in experiments/ using it to enable
the radios. Running this before booting Linux will make the network
controller devices show up in lspci, even if Linux lacks an SMC driver.
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>

Add smc.py script to enable radios

---

src/smp.h

The full 4-argument version of smp_call is `smp_call4`; smp_call doesn't exist.

smp: Fix smp_call macros with fewer than 4 arguments

---

proxyclient/m1n1/proxyutils.py

Fix the `gstr` typo so that `print(hv.adt)` works as expected.

proxyclient: Fix typo in LazyADT str implementation

---

src/start.S
src/startup.c
src/uart.c
src/uart.h
src/wdt.c
src/wdt.h

The M1 Pro/Max Macs use a different base address for the UART and the WDT than earlier models.
Remove hardcoded base addresses constants and replace them with loads from the ADT.
- The base address of the WDT is already retrieved in `wdt_disable`; also use this address when triggering a reboot.
- Retrieve the base address of `uart0` in `uart_init`. If the operation fails, the error will be signaled on the early uart (if not disabled).
- The early debug UART can’t use the ADT (or shouldn’t) so it is now disabled by default. To enable it, add
```
-DEARLY_UART -DEARLY_UART_BASE=0xuart_address
```
to the CFLAGS.

Remove hardcoded UART/WDT addresses

---

proxyclient/m1n1/hv.py
proxyclient/m1n1/proxy.py
src/hv_vuart.c
src/iodev.c
src/iodev.h
src/kboot.c
src/pcie.c
src/uartproxy.c
src/usb.c
src/usb.h
src/usb_dwc3.c
src/utils.c
src/utils.h

Adds support for the 3rd USB-C on the 2021 Macbook Pro.
Tested on Macbook Pro 14" and Mac Mini.

usb: support more than 2 usb-c ports

---

src/aic_regs.h

Change aic1 reg size from 0x4000 to 0x8000 for macos to boot under the hv when doing irq tracing to avoid hypervisor IPA unmapped error.
Signed-off-by: Jean-Francois Bortolotti <jeff@borto.fr>

Fix aic1 reg size

---

proxyclient/experiments/smc.py

Update experiments/smc.py to use fw/smc.py's new API.
Fixes: b9ddd74c02c7 ("hv/trace_smc.py: Add SMC tracer")
Signed-off-by: Jean-Marc Ranger <jmranger@hotmail.com>

experiments/smc.py: Adapt to API change in SMCEndpoint

---

proxyclient/m1n1/hw/dart.py
proxyclient/m1n1/trace/dart.py

- update PTE.BIT(1) annotation to disable sub-page protection
- initialize the PTE type from compatible property in DARTTracer, fixes tracing on M1 Pro/Max

m1n1 dart fixes

---

src/hv_vm.c

A trivial fix since the input data are already aligned in most of cases, so the problem won't lead to something like crash. But BIT() should be the correct choose in ALIGN_UP/DOWN.

hv_vm: fix an alignment problem in hv_map

---

src/rtkit.c

Needed for the `RTKIT_SYSLOG` optional define.

rtkit.c: Add config.h include

---

src/afk.c

probably even useful to not hang forever even if we require macOS >= 12.
If the co-processor crashes afk_epic_poll will always fail which results
in afk_epic_rx getting stuck in an infinite loop calling afk_epic_poll
again and again.
This happens with e.g. old/incompatible DCP firmware.
Make sure the m1n1 proxy still works in those cases by propagating the
error correctly.

afk: propagate failures in afk_epic_rx correctly

---

src/dcp.c
src/nvme.c
src/rtkit.c
src/rtkit.h

ANS needs to be sent to power state 0x01, otherwise it can't be reset.
I'm pretty sure I saw the string "hibernate" in some DCP firmware (or maybe even in some kext) for the 0x10 state fwiw

rtkit: add rtkit_{hibernate,sleep} and use them for DCP and ANS2

---

proxyclient/m1n1/utils.py

ehexdump is similar to chexdump, and uses CP437 control characters
and Braille to improve eyeballability of character output.
Signed-off-by: Mikhail Gusarov <dottedmag@dottedmag.net>

proxyclient: utils.py: add ehexdump()

---

src/kboot.c

Fixes adding "u-boot,dm-pre-reloc" to all required power-management
nodes on t600x.

kboot: reload dt offset after dt_set_uboot_dm_preloc

---

proxyclient/m1n1/loadobjs.py

For those of us who can't write assembly but still need to run code on
the other side.
```
>>> from m1n1.loadobjs import *
>>> lp = LinkedProgram(u)
>>> lp.debug_printf("hello from the other side (%d)\n", 42)
TTY> hello from the other side (42)
0x1f
>>> lp.load_obj("build/test.o")
>>> lp.test()
TTY> hello from loaded object
0x19
>>> lp.clear_objs()
```
--
I don't know if anybody else will find this useful but as it doesn't hook into anything maybe it can live in mainline.

m1n1.loadobjs: Add util for loading objects on target

---

src/exception.c

Do not forget to clear the L2C_ERR flags in silent mode also. This is
necessary for proper recovery.
Signed-off-by: Martin Povišer <povik@protonmail.com>

exception: Fix silent mode

---

proxyclient/experiments/dcp.py
proxyclient/m1n1/fw/dcp/dcpep.py
proxyclient/m1n1/fw/dcp/ipc.py
proxyclient/m1n1/fw/dcp/manager.py

Works currently via vUART under HV with dcp tracing. On bare metal dcp crashes immediately after rtkit start.This matches the behavior seen with the Linux driver although they fail with different messages in crashlog.
bare metal dcp.py: `Message 1: MMU out of tables: 200,200,0`
Linux: `Message (id=1): IOMFB int_handler_gated: failure: axi_wr_err [0x80000400]`

experiments/dcp.py: t600x support

---

src/hv.c

DCP will otherwise not be useable from the guest system.

hv: Hibernate DCP in hv_init

---

src/pcie.c

The PCIe 4 link speed is only described as "target-link-speed" in the
"lan-10gb". This changed in macos 12.3 or earlier. Verified on Mac
Studio and with the template Mac Mini ADT.
Reported-by: Jeff Geerling <geerlingguy@mac.com>

pcie: Set correct link speed for 10gb ethernet

---

proxyclient/tools/linux.py

-t is optional, we may not have a tty_dev, so we can avoid trying to
grab the baudrate from it if it's unspecified.
We don't want to use dtb_addr for booti; this is the unmodified payload.
m1n1 will load it and add bits to it at a separate address for passing
on to U-Boot.  For booti purposes, we actually want the augmented FDT
rather than the user-specified.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>

proxyclient: tools: fix linux U-Boot support

---

proxyclient/tools/freebsd.py

The differences are documented in the script itself, but the main odd
bit is that we pass the provided kernel as an initramfs.  Our modified
loader will probe for the initramfs start/end props in FDT and put up
a memdisk that we load the kernel from.  This choice was made for two
reasons:
1.) Avoid ad-hoc interpretations of a memory region in m1n1, it doesn't
care if we actually passed it an initramfs or not anyways.
2.) We already had some code on hand to do this in our loader, so I
suspect we've done similar shenanigans elsewhere anyways.
This also requires a U-Boot change to allow bootefi of an arbitrary
location, as long the size is provided.
The alignment constraints for loader/kernel were kept arbitrarily.  The
kernel will be bounced anyways by loader. I don't recall what
alignment …

proxyclient: tools: add a FreeBSD loader

---

proxyclient/m1n1/hv.py

event_mmio() uses 'start' kwarg since 'zone' conflicts with
add_tracer()'s argument of the same name.
Fixes
TypeError: HV.add_tracer() got multiple values for argument 'zone'

m1n1.hv: fix argument names in HV.trace_range()

---

README.md

As far as I can tell this is the best replacement for the (now dead) link. If there is a better wiki page to link to, let me know.

Fix m1n1 wiki link

---

src/utils.c

Commit 9c795fbdbf445d144d331ff2a19a0f42fe0fc190 introduced the pair of
WFE and SEV for spinlock, but it caused delays of tens of seconds. A
possible explanation for the delay is lack of data synchronization
barrier between the store instruction and SEV instruction.
Arm Architecture Reference Manual for A-profile architecture (issue H.a)
says:
> Arm recommends that software includes a Data Synchronization Barrier
> (DSB) instruction before any SEV instruction. The DSB instruction
> ensures that no instructions, including any SEV instructions, that
> appear in program order after the DSB instruction, can execute until
> the DSB instruction has completed.
However, inserting a DSB instruction still didn't resolve the delay.
The exclusive load is an alternative to the SEV instruction. The …

utils: Use exclusive load to wake up from WFE

---

proxyclient/experiments/ohmmeter.py
proxyclient/m1n1/hw/i2c.py

Add script which prints out the (rough) measured impedance of connected
headphones on machines with the CS42L84 jack codec (2021 Macbook Pros).
$ proxyclient/experiments/ohmmeter.py
Waiting for plug... measuring... 64.3 ohms... yanked
Waiting for plug... measuring... 697.1 ohms...
Signed-off-by: Martin Povišer <povik@protonmail.com>

experiments/ohmmeter.py: Make CS42L84 your ohmmeter

---

proxyclient/experiments/agx_1tri.py
proxyclient/m1n1/hw/pmu.py
proxyclient/m1n1/hw/spmi.py
proxyclient/tools/reboot.py
proxyclient/tools/reset_panic_counter.py
proxyclient/tools/run_guest.py

Replace the handrolled implementation in experiments/agx_1tri.py and
tools/reset_panic_counter.py.
In addition reset the panic counter in reboot.py and run_guest.py. If
can reboot or start guests the boot process works fine and macOS
recovery needs to leave us alone.

m1n1.hw.pmu: Add SPMI PMU support for resetting the panic counter

---

src/afk.c

The previous code loops infinitely when m1n1 is installed on a macOS 13 stub, with the message:
```
EPIC: got unexpected message 00:0032 during iface start
```
This patch doesn’t fix the underlying problem but allows m1n1 to successfully start.

AFK: limit number of tries in start_interface

---

proxyclient/hv/trace_mesa.py

Probably worth treating this more like an RFC than a proper PR,
since this doesn't actually do anything particularly useful without the
SEP tracer. 
The only really useful stuff you can get out of this is:
* A pointer to an address which _seems_ to store the actual fingerprint image
* The fingerprint image (though I haven't tried undumping this into a binary file)
* That the command buffer is encrypted
* Its behaviour is consistent across reboots, though the data found in its memory isn't
* There is a SIO endpoint (0x2) that seems to send/receive data when a finger is placed on the
sensor, but trying to read from it in the same way as other EPs crashes the hypervisor
We could probably systematise the reading of the IOVA regions, but I've just been running
iomon.poll() after halting the …

hv/trace_mesa.py: add mesa tracer

---

proxyclient/hv/trace_mesa.py

Some changes in m1n1 meant that the tracer as it was before would not work without manual intervention. This has been fixed.
Out of interest, we now log the SPI control registers. Nothing interesting to see though.
I have also de-gored some redundant lines and made cosmetic improvements to how it logs. For ease of reading control
sequences, the tracer now dumps out what I suspect is encrypted fingerprint data plus some sort of header into a file. It also
no longer monitors the SIO "config" address space since we're not interested in how the SIO interface itself is configured.
This can be re-enabled by uncommenting the relevant lines anyway.

Minor improvements to trace_mesa

---

proxyclient/m1n1/hv/__init__.py
proxyclient/tools/run_guest.py

Hello!
Had to repost because the last pull request had issues, also cleaned up some code
As part of my efforts to boot Windows on Apple silicon Macs successfully, part of that meant adding raw binary support to the hypervisor scripts (This is to allow raw binary UEFI images to be executed directly using the run_guest.py script instead of being forced to wrap them in Mach-O headers or concatenate them to a Mach-O wrapped m1n1 payload, allowing for quicker build and test cycles)
I wanted to contribute this change back to mainline m1n1 as I feel that it'd be a really nice to have addition to the hypervisor so that everyone can benefit from being able to directly load raw binaries using the run_guest script.
Most of the code from the load_macho logic ended up working perfectly for the …

add raw binary support to HV scripts

---

proxyclient/m1n1/hv/__init__.py

Hello,
As @svenpeter42 indicated to me recently, my initial patch enabling raw binaries to be loaded inside the m1n1 hypervisor (original pull request #225) had a bug/omission in it which caused XNU symbols to no longer work properly as sym_offset was defaulting to 0.
This pull request fixes that issue/errata and XNU symbols should work properly now as they did prior to #225, and all raw binary loading functionality should also work as it does in #225.
Technical details:
The fix did require me to add two parameters to load_raw, use_xnu_symbols (whose value comes from self.xnu_mode, defaults to False in the raw binary case and the case where symbols are not loaded with XNU kernels, it's only true if symbols are specified with an XNU kernel), and vmin (only used if use_xnu_symbols is true, …

Fix bug preventing XNU symbols from working

---

src/hv_exc.c

Boot panics due to what appears a timeout without ignoring this sys_reg
in m1n1.

hv_exc: Add s3_7_c15_c3_1 sysreg passthroughs for t8112/macos 12.4

---

src/kboot.c

With the stuff passed in to /chosen by u-boot and m1n1, this gets us pretty close to feature parity with DMI in terms of having
meaningful system "personalisation" information available to userspace for consumption.

Pass machine serial number into FDT

---

src/kboot.c

"simple-bus" restricts the node names to predefined list. "soc" looks
like the most appropiate name considering the dies are M1 Max SoCs.

kboot: Adapt multi-die handling to linux submitted DT

---

proxyclient/m1n1/proxy.py

Commit 6a1a9bfc3c942e33142754f323078fd838c72def raised the limit in proxy.c but not in the Python code.

m1n1.proxy: increase p.call max args to 5 to match proxy.c

---

Makefile
src/dart.c
src/dart.h
src/devicetree.c
src/devicetree.h
src/display.c
src/kboot.c

- Add the boot iommu mappings for dcp/disp0 to the FDT based on https://lore.kernel.org/asahi/20220923123557.866972-1-thierry.reding@gmail.com
- lock dart-disp0
Matching kernel tree is https://github.com/jannau/linux/tree/asahi-dcp-september

preserve iommu mappings for DCP/disp0

---

proxyclient/hv/trace_isp.py
proxyclient/m1n1/hw/isp.py
proxyclient/m1n1/trace/isp.py

Image Signal Processor is a co-processor in charge of Facetime camera
in Apple laptops. This tracer is based on ISP found in M1 processor.
The ISP in M1 SoC exposes seven inter-process communication channels.
Using those channels Application Processor (AP) can perform a variety of
task in the ISP and viceversa. All channels seems to be bidirectional, with
unique exception of TERMINAL channel.
DART translation is used often to translate control structures passed
over IPC channels to IO virtual addresses.
How those channels are used is still unclear but tracer should allow us
to dive deep on high-level protocol to communicate with Facetime camera.
ISP exposes also some I2C peripheral and SPMI registers but I haven't
dive into their working or purpose.
This is early implementation, that …

hv/trace_isp.py: add ISP tracer

---

proxyclient/experiments/aop.py
proxyclient/experiments/mmio_sweep.py
proxyclient/hv/trace_aop.py
proxyclient/m1n1/adt.py
proxyclient/m1n1/fw/afk/epic.py
proxyclient/m1n1/fw/afk/rbep.py
proxyclient/m1n1/fw/aop/__init__.py
proxyclient/m1n1/fw/aop/bootargs.py
proxyclient/m1n1/fw/aop/ipc.py
proxyclient/m1n1/hw/admac.py
proxyclient/m1n1/hw/dart.py
proxyclient/m1n1/proxyutils.py
proxyclient/m1n1/trace/__init__.py
proxyclient/m1n1/utils.py
proxyclient/tools/admac_stream.py

This has extension of `experiments/aop.py`, addition of AOP tracer and some other tweaks.
To cite the key commit:
experiments/aop.py: Extend AOP experiment, add tracer
The AOP uses an 'EPIC' protocol similar to the one other coprocessor
firmware is using but not in the exact same version. Add code for
tracing the AOP calls and extend the aop.py experiment with the client
side of it. Include description of audio calls and some other calls
related to sensor discovery.
Furthermore, in experiments/aop.py, do some AOP audio setup. Once that
is done we can start streaming samples from the internal microphones by
making what AOP considers power state adjustment calls. That is, we
adjust the power state of a 'hpai' device, first to a 'pw1 ' stage,
then to 'pwrd' stage.
So, to see microphone …

Tapping the internal microphones

---

proxyclient/experiments/dcp.py
proxyclient/m1n1/fw/dcp/ipc.py
proxyclient/m1n1/fw/dcp/manager.py

Main change of this pull request is to transfer the devices maximal backlight brightness from the ADT to the devicetree. It is also sneaking in a change to enable `disp0_dart` to avoid breaking simpledrm when booting a DCP enabled devicetree with a m1n1 revision which doesn't lock it.
Adds annotations for the backlight control fields in swap_rec.
In addition there are `experiment/dcp.py` which should allow running it on every device and eventually support dcpext if everything else is set up.

Panel backlight

---

src/kboot.c

* firmware version was only set for t600x dcpext nodes.
* mapping of `dcp_txt` failed on m2 since the same reserved memory node has to be used for `dcp` and `dcpext`

dcpext fixes for setting firmware version and m2 support

---

Makefile
proxyclient/m1n1/adt.py
proxyclient/m1n1/hv/__init__.py
proxyclient/m1n1/hv/types.py
proxyclient/m1n1/hv/virtio.py
proxyclient/m1n1/hv/virtutils.py
proxyclient/m1n1/proxy.py
proxyclient/m1n1/proxyutils.py
proxyclient/m1n1/utils.py
proxyclient/tools/run_guest.py
src/hv.h
src/hv_virtio.c
src/kboot.c
src/proxy.c
src/proxy.h

This allows one to access host m1n1 sources from within the system running in hypervisor. Once you arrange for the virtio peripheral both in hypervisor code (`self.attach_virtio(Virtio9PTransport(), 0x2_2000_0000, 382)`) and in the devicetree, you run
mount -t 9p -o transp=virtio m1n1 /mnt
to mount the sources on guest. One use case of it is using m1n1 regmaps over kernel's internal regmap structures (as alluded to by the extra commit).
Performance is not great since the hypervisor stops to handle each 9P call but it's not impractical.
Direction I think this should be expanded in:
* Allocate the IRQs/register range automatically
* Insert the peripheral into ADT
* Have guest m1n1 transfer it from ADT to FDT
Let me know if you think this is fine for inclusion.

hv: Add 9P virtio peripheral

---

version.sh

The new version.h script uses a few bashisms which is always a bit of a problem on debian/ubuntu where the default sh is dash.

Remove bashisms

---

src/kboot.c

- use `/vram` for the framebuffer, if m1n1 reallocates the framebuffer due to higher configured resolution only `/vram` is updated
- add `memory-region-names` properties so the DCP driver can get the framebuffer. There are two use cases for this:
1. with `drm_aperture_remove_conflicting_framebuffers()` replacing simpledrm's kms device seems to work reliable  
2. might be required for seamless switching from simpledrm to dcp (I have not checked how that is supposed to work)
- use unique compatible strings for each reserved memory region

kboot/dcp: reserved-memory updates

---

src/kboot.c

U-Boot is moving to a new set of tags to indicate devices that should be bound/probed in early bootstrap phases.  Add 'bootph-all' tags from the new bindings such that probing the serial port early on in U-Boot continues to work and doesn't hang the system.

kboot: Add new U-Boot driver model 'phase-tags'

---

proxyclient/m1n1/fw/asc/ioreporting.py

SMC provides buffer from its MMIO space. Since the macOS 13 SMC firmware the firmware crashes when ACK-ing a GetBuf which provided a buffer.

m1n1.fw.asc.ioreporting: Support IOP provided buffers

---

proxyclient/hv/trace_cd3217.py

Interface (as used by macOS) is simple enough to skip register definitions.

hv/trace_cd3217: Add tracing for TI/Apple cd3217 USB type C controller

---

src/dart.c
src/dart.h
src/dcp.c
src/display.c
src/rtkit.c

This prevents crashes while mapping the carved out memory for the framebuffer. DCP is set up differently on M2. The DART stream id is `5` instead of `0` and it uses the top half of 36-bit IOVA space instead of relying on `asc-dram-mask`. The HDMI output does not work yet. It appears to require setup to connect `disp0` to the DisplayPort to HDMI converter to allow connecting it to the ThunderBolt 4 ports for a second display output.
Further changes for the M2 Pro Mac mini are expected.

M2 Mac mini display support, part 1

---

proxyclient/experiments/dart_dump.py

Fixes: 183991ca1983 ("m1n1.hw.dart: Hide all DART variants behind common interface")

experiments/dart_dump.py: Fix register dump after 183991ca1983

---

src/adt.c
src/iodev.c
src/vsprintf.c

Add a space between '//' and '#' to satisfy clang-format 15

---

tools/apple_regs.json

Hello,
(trying this again to make sure the commit passes the DCO check lol)
Recently my work on getting Windows initially working on M-series Macs required me to find a way to trap PMUv3 accesses from the OS. Seeing as other hypervisors and VMMs like Parallels or UTM also would have encountered the same problem, I figured there should be an MSR that allows this behavior.
Turns out, HACR_EL2 bit 56 is the one that allows EL2 to trap all accesses to PMUv3 registers from EL1. This PR documents this bit and it's purpose by updating apple_regs.json. This should be a very simple PR to document a very useful bit for OSes which don't accommodate non-standard PMCs.
I was not the one who originally found this, original source of information here: …

Document HACR_EL2[56] and it's purpose

---

src/kboot.c

With the dummy framebuffer (on a headless M2 Pro mini) it seems that there is no iommu mapping for the framebuffer.
The code added in commit 21dc62273565 makes this fatal. Instead, print the warning but skip adding the mapping
to the device tree.

Fix booting with dummy framebuffer

---

proxyclient/experiments/touchbar_apple_prepare.sh
proxyclient/experiments/touchbar_bad_apple.py
proxyclient/experiments/touchbar_rainbow.py

Let ffmpeg rotate, align to stride and convert to RGBA. Do not allocate a framebuffer for every frame.

experiments: Optimize bad apple video playback

---

proxyclient/tools/run_guest_kernel.sh
src/payload.c

To support modules during development with `run_guest_kernel.sh` a cpio archive with matching modules can be created with `make dir-pkg` and `usr/gen_initramfs.sh` in the kernel dir. A specially prepared initramfs can use the modules and make them available to the OS in a similar way as the vendor firmware.

Support concatenated initramfs images

---

src/afk.c
src/dcp_iboot.c

minor changes for the 13.3 DCP firmware fixes display init on mac mini (2020) and mac studio (2022)

Support display init with DCP 13.3 firmware

---

proxyclient/m1n1/asm.py

https://github.com/AsahiLinux/m1n1/commit/e19e74be8b7d5f3643cbb4237ee6b8ba2a7d8578 added support for clang, but unfortunately it also broke gcc on Linux, as I'd get:
```
$ ./chainload.py ../../build/m1n1.macho 
m1n1 base: 0x10002750000
LOAD: _HDR 16384 bytes from 0 to 0
LOAD: TEXT 163840 bytes from 4000 to 4000
LOAD: RODA 49152 bytes from 2c000 to 2c000
LOAD: DATA 393216 bytes from 38000 to 38000
ZERO: 196608 bytes from 0x98000 to 0xc8000
LOAD: PYLD 0 bytes from 98000 to c8000
SKIP: 67108864 bytes from 0xc8000 to 0x40c8000
Fetching ADT (0x00070000 bytes)...
Total region size: 0x80c000 bytes
Loading kernel image (0xc8004 bytes)...
...............
Copying SEPFW (0x73c000 bytes)...
Adjusting addresses in ADT...
Pushing ADT (445900 bytes)...
Setting secondary CPU RVBARs...
cpu1: [0x210150000] …
```

m1n1.asm: make it work again with gcc

---

proxyclient/m1n1/proxy.py
proxyclient/tools/picocom-sec.sh

Small improvement to the out-of-the-box experience when using maOS as tethered boot host
- use `/dev/cu.usbmodemP_03` and `/dev/cu.usbmodemP_01` for `picocom-sec.sh` and `proxyclient` respectively

Small improvement to tethered boot support from macOS host

---

src/kboot.c

There is at least on Macbook Pro (M1, 13-inch) with missing "multi-touch-calibration" in the ADT. Disabling the device as error handling instead of refusing to boot the kernel.

kboot: disable touchbar on missing calibration data

---

src/adt.c
src/kboot.c

Fixes an issue in `adt_get_reg()` which affect only the range parsing in `spinor`
Can be merged without effects before the device tree updates in https://github.com/AsahiLinux/linux/pull/179

Parse nvram size from ADT

---

Makefile
src/afk.c
src/afk.h
src/dart.c
src/dcp.c
src/dcp.h
src/dcp/dpav_ep.c
src/dcp/dpav_ep.h
src/dcp/dptx_phy.c
src/dcp/dptx_phy.h
src/dcp/dptx_port_ep.c
src/dcp/dptx_port_ep.h
src/dcp/parser.c
src/dcp/parser.h
src/dcp/system_ep.c
src/dcp/system_ep.h
src/dcp_iboot.c
src/dcp_iboot.h
src/display.c
src/nvme.c
src/rtkit.c
src/rtkit.h
src/smc.c
src/smc.h

Initialize the HDMI output of M2+ desktop Macs releases in 2023.
- Mac mini (M2/M2 Pro) and Mac studio (M2 Max) should work (tested on both mini models)
- Mac Pro / studio (M2 Ultra) are different but I would expect it to work as well
- only one HDMI port on the Mac Pro works (the one driven by die 1), no idea which
- high res displays might not work if they require different phy parameters

M2+ desktop dcp/dptx HDMI output support

---

src/firmware.c

Prior to this patch, failure of firmware_set_fdt is silent, because
it returns the value of fdt_setprop rather than issuing an error if
fdt_setprop fails.

Issue error message if firmware_set_fdt fails

---

src/kboot_gpu.c

Without this property u-boot will add reserved memory regions to the EFI memory map with the wrong type. This results in Linux mapping it and thus breaking the intended use in the asahi driver.

kboot/gpu: Add "no-map" property for reserved memory nodes

---

proxyclient/experiments/dcp_iboot_m2pro.py
proxyclient/m1n1/fw/dcp/dcpav.py

Mostly as sanity check to compare a C implementation against. I would expect this to work on the M2 Max Mac Studio as well. M2 Ultra Mac Studio and Mac Pro hopefully work after replacing dcp0/disp0 with dcpext0/dispext0.
lpdptx-phy and dptx-phy look mostly identical. The lpdptx-phy sequence did not work on j473 but worked on j474s with the same display. I haven't looked but there might minor differences. lpdptx-phy could support DisplayPort 2.0 for 8k support without dsc/chroma subsampling.

Support M2 Mac Mini in experiments/dcp_iboot_m2pro.py

---

src/afk.c
src/dcp.c
src/dcp/dpav_ep.c
src/dcp/dptx_phy.c
src/dcp/dptx_port_ep.c

Fixes display initialization from stage 1 m1n1. 20ms looked reliable on
j473 but let's add 25% safety margin. Someone with more motivation (and
HW serial) to do repeated `kmutil configure-boot ...` can try to
minimize this and test on t602x
Also silence some afk/dptx printf() by converting them to dprintf().

DPTX: add 25ms delay to make 1st stage display init reliable

---

src/smc.c

clang 17 now enforces strict prototyping. add void to the parameters to fix building with clang going forward.

smc: fix smc_init() definition

---

proxyclient/m1n1/shell.py

This shouldn't crash the shell — it's enough to warn about it and carry on.

m1n1.shell: carry on if saving history fails

---

data/makelogo.sh

Use /bin/sh instead which should work on most posix platforms. Fixes OpenBSD.

bash is not available everywhere

---

src/adt.c
src/hv_vm.c

If DEBUG is not defined, the compiler doesn't look at the arguments to dprintf().  This has led to dprintf() bitrotting over time, referring to variables that no longer exist, or by the wrong type, etc.
Here, I've tried to fix all the dprintf() calls to the best of my ability, by comparing them to nearby calls that do compile, and looking through the git history to understand the original intent.
I imagine I've probably got one or two things wrong due to not being familiar with the code, but I think this is mostly right.

Fix build with -DDEBUG

---

proxyclient/m1n1/adt.py

When I tried to use the proxyclient shell, I got:
"Exception parsing /device-tree/arm-io/dart-dcp.dapf-instance-0 value […]"
I laid out the hex dump in a text editor, and added line breaks every 56 bytes (the former size of DAPFT8110B):
```
0000703b020000000080713b0200000020000000000000000000000000000000000000000000000000000000000000000003010000000000
40723b020000000080723b020000002000000000000000000000000000000000000000000000000000000000000000000301000000000000
003b020000007f73073b02000000200000000000000000000000000000000000000000000000000000000000000000030100000000000028
3d020000000040283d020000002000000000000000000000000000000000000000000000000000000000000000000301000000000080003d
020000000380003d020000002000000000000000000000000000000000000000000000000000000000000000000301000000000000e …
```

 m1n1.adt: introduce yet another DAPFT8110 variant 

---

src/smp.c
src/soc.h

I only can easily find the T6031/T6034/T8122 values.
If there is a T6030, the value is not in the same place I found these.

Add initial M3 values for CPU_START_OFF

---

proxyclient/m1n1/ishell.py
proxyclient/m1n1/ishell_ext.py
proxyclient/tools/ishell.py

Same functionality as the readline shell, but based on
ipython so that it has nicer help/autocomplete/etc
I moved the support to do monitor polling/simd handling into an ipython extension
for this shell.
It currently does not auto-load (unless you put it in your profile)
This can be changed if we want it.

Add ipython shell to proxyclient

---

Makefile
config.h
proxyclient/hv/trace_dcp.py
proxyclient/m1n1/fw/dcp/dcpep.py
proxyclient/m1n1/fw/dcp/ipc.py
src/dcp.c
src/dcp.h
src/dcp/dptx_port_ep.c
src/dcp/dptx_port_ep.h
src/display.c
src/display.h
src/kboot.c

This switches j473, j474s and j475c to dcpext(0) as display co-processor for HDMI out. Main reason is that dcpext(0) wakes up after sleep + reset. This simplifies handling in m1n1 a little.
This contains the tracing/m1n1.dcp changes for the rarely used OOB ASYNC callback channel.
In addition holds some minor fixes. The die number fix should be cosmetically, dcp firmware doesn't seem use it for something essential in a dptx connection.

Use dcpext for all M2 desktop devices.

---

proxyclient/m1n1/adt.py

On m3, these previouly expected-to-be-constant fields have exciting
non-constant values.  This updates adt.py to allow them to be
non-constant.  The second field is also really a flags field,
though i could not tell you all the flags involved.

Support non-constant unknown values in adt.py

---

src/usb.c

This patch is a workaround for the lack of SPMI support in usb.c
Newer machines use SPMI and a different type C power controller.
This patch still lets us make the USB ports work by skipping power-on and just enabling the phys

Workaround new USB using SPMI instead of I2C

---

Makefile
README.md

This is useful for importing m1n1 into IDEs which depend on parsing compiler options to extract information about the project, such as CLion.

Add option for building verbosely

---

src/nvme.c

For some reason the ans node for t602x devices has an empty "clock-gates" property. Use the MMIO address instead to determine on which die the device is.
Fixes: 34f49a5 ("nvme: assume die 0 if clock-gates not set")

nvme: t6022: Derive die from nvme_base address

---

proxyclient/experiments/avd.py
proxyclient/experiments/avd_e.py
proxyclient/experiments/avd_fw.py
proxyclient/hv/trace_avd.py
proxyclient/m1n1/fw/avd/__init__.py
proxyclient/m1n1/fw/avd/decoder.py

PR'd because the driver prototype has been stable for a while.
Sorry for bothering  you over the holidays, but there's not much to see here. Most of the juice is over at:
https://github.com/eiln/avd.git
The kernel driver (m1n1.fw.avd) only really pipes the instruction stream into the respective hardware FIFOs and then hopefully hushes the interrupt lines. Most of the work (bitstream syntax parsing and instruction generation) is done in the avid repo above.
I'm hoping to keep this userland-kernel separation in the very imminent actual driver.
experiments/avd.py: Decode on the command line. Read file for usage.
experiments/avd_e.py: Decode via emulated instruction stream.
experiments/avd_f.py: Decode via Cortex-M3 firmware (for debugging).
hv/trace_avd.py: Tracer. Read file for usage. …

Start of Video Decoder work

---

src/kboot.c
src/sio.c
src/sio.h

Use a struct instead of global variable to hold the necessary setup information. This allows executing the setup for both sio instances. In addition change the status to "okay" so that sio can remain disabled if the setup fails.

sio: Rework sio init for dual die SoCs

---

src/dart.c
src/dcp.c

On  t8103/t600x devices the firmware mapping check needs to mask out `asc-drm-mask`. Fixes HDMI output initialization in stage 1 on M1* desktop devices.

dcp: Fix firmware mapping check on t8103/t600x

---

src/iodev.c
src/iodev.h
src/kboot.c

Requires for easy access `CONFIG_MTD_PHRAM` but I guess can be still accesses through /dev/mem on systems missing this.
The additional IODEV for the log console is a little bit ugly since it can't be added before `IODEV_USB0` to keep backwards compatibility with python m1n1 but it shouldn't be handled like the USB IODEVs.

Add ADT and m1n1 stage 2 log as MTD phram reserved memory nodes

---

src/kboot.c

(by not sending anything in that case)

z2: Deal with missing calibration data

---

src/chickens.c
src/cpu_regs.h

This register is used to store AMX context information.

Give AMX context reg a name.

---

Dockerfile

Install the rust toolchain in the Docker container so it can be used when building with `CHAINLOADING=1` too

docker: install rust toolchain for stage1 builds

---

proxyclient/m1n1/hw/aes.py

Fixes: 183991ca1983 ("m1n1.hw.dart: Hide all DART variants behind common interface")

hw/aes.py: Fix python error after 183991ca1983

---

src/clk.c

AOP does it itself, and doing it in m1n1 confuses it into not being able to boot.

clk: Revert PDM clock initialization.

---

src/aic.c
src/aic.h
src/aic_regs.h
src/kboot.c

Support new version of AIC used by M3

Support AIC version 3

---

src/cpufreq.c

This seems to work, and matches the info i can find.

Support cpufreq for t6031

---

proxyclient/tools/freebsd.py

The FreeBSD script added in #185 required patching u-boot since it specified the loader base/size in a non-standard way. This changes the way arguments are passed to the bootefi command so it works with the asahi u-boot fork which I've been using. I also changed the case where the loader isn't specified to have u-boot boot from the nvme since I have that driver functional enough to have it mount the root fs now.

proxyclient: Modify FreeBSD loader to use standard U-Boot bootefi cmd

---

proxyclient/m1n1/hv/__init__.py
proxyclient/tools/chainload.py
src/smp.c
src/startup.c

M3 devices use the first CPU core in the first performance core cluster for booting while the efficiency core cluster remains the first cluster. Use the CPU core's state property to determine the boot CPU.
Supersedes #369
Tested on M3 MacBook Pro (2023, 14-inch).

Support arbitrary boot CPU core

---

src/pmgr.c

The id1 field used on oder SoCs is not constant 0 for all devices on t8122. Instead just compare the id1 fields of the two first devices. Fixes "pmgr: Failed to find parent #36 for IOA0\n" errors in pmgr_init().
Fixes: fb59dc03ca9a ("pmgr: Fix struct for older SoCs")

pmgr: Fix false positive u8 pmgr ID detection on modern SoCs

---

proxyclient/m1n1/hv/__init__.py
proxyclient/m1n1/proxy.py
proxyclient/m1n1/proxyutils.py
proxyclient/m1n1/tgtypes.py
proxyclient/tools/chainload.py

Not an elegant solution but at least it is working. The main issue with using unions / conditional construct elements is their size can't be determined in in proxy.readstruct().

m1n1: Handle BootArgs revisions 1, 2 and 3

---

src/display.c
src/main.c
src/utils.c
src/utils.h

Supersedes #428. Not sure if the changes to `display_get_config()` are the right thing to do here.

Contain all display init logic within display.c

---

src/kboot.c
src/kboot_gpu.c

This should make the behavior with and without u-boot (mostly) consistent. I think u-boot also adds mem ranges for `no-map`  reserved ranges (then the kernel doesn't map them as requested), but that shouldn't make much of a difference.

Allow !no-map GPU reserved ranges and map them

---

src/kboot.c

m1n1 v1.4.18 with the device trees from asahi-6.12.10-2 need on Mac Studio (2023, M2 Ultra) at least 340 bytes more than the available 64K. bump this to 96K and add a warning if the remaining space is less than one 16K page.

kboot: Allocate 96K for device tree modifications

---

src/kboot.c

dt_set_display() relied on display_get_config() returning the default config entry as it is only interested on the device tree alias for the primary dcp. This is always "dcp" except for devices with a config. Since commit 8508526 ("display: contain all display init logic within display.c") it however returns NULL if ADT dcp node specified in the config does not exists. This is the case for M2 Pro and Max macbooks which use "dcp0" instead of "dcp".
Fixes: 8508526 ("display: contain all display init logic within display.c")

kboot: Prevent NULL pointer dereference in dt_set_display()

---

Makefile
src/fb.c
src/payload.c
src/payload.h

Supports a custom logo appended as first payload.
Build system integration currently requires that the custom logo PNGs are copied to 'data/${CUSTOM_{128,256}.png` and ImageMagick is installed.  
`make LOGO=${CUSTOM}` will then create a m1n1.bin with the custom logo. In addition m1n1-asahi.bin is built which carries the Asahi Linux logo.

fb: Add custom boot logo support

---

src/smp.c
src/utils_asm.S

da3519de142 introduced the additional argument cpufeat_global_sleep to cpu_sleep but did neither update its prototype nor the call inside proxy.c. Instead of adding a new argument just directly load the value of cpufeat_global_sleep and use it instead.
Fixes: da3519de142

utils/proxy: Fix cpu_sleep global sleep handling

---

src/kboot.c

The Mac Pro (j180d) has 2 ethernet nics. Add "ethernet1" as alias so the MAC address of the second nic is transferred to the devicetree as well.

kboot: Add ethernet1 alias

---

.packit.yaml

These have been failing for a while now

packit: remove fedora-rawhide-ppc64le builds

---

README.md

The wiki link on the README is dead. This commit replaces it with the same page on the asahi docs.

Fix m1n1 wiki url

---

src/payload.c

The pre-configured property was ignored and lacked the "asahi," prefix that we use for other version properties.

payload: Fix m1n1 stage 1 version passing

---

src/payload.c

Don't attempt to modify string constants which live in read-only memory.
Fixes: 75329c5 ("payload: Fix m1n1 stage 1 version passing")

payload: Fix running payloads in stage1

---

src/kboot.c

Devices with exchanged WLAN/BT omit calibration data in the ADT. The calibration data isa stored in Facory Data Recovery partition instead. Continue booting in such cases. WLAN and BT driver will fail to probe until an alternative way to provide the calibration data is implemented.
The only models with replaceable WLAN/BT modules are to my knowledge Mac Pro (M2 Ultra) and Mac mini (M4/M4 Pro).

Handle missing WLAN/BT calibration data gracefully

---

Makefile

Allows building m1n1's rust components on systems without rustup support.  Removes the need to install the
aarch64-unknown-node-softfloat toolchain.  But it does require the rust-src component to be installed.

Makefile: Optionally build rust code with -Z build-std

---

proxyclient/experiments/mmio_sweep.py
proxyclient/m1n1/adt.py
proxyclient/m1n1/hv/__init__.py
proxyclient/m1n1/hw/pmu.py
proxyclient/m1n1/proxy.py
proxyclient/m1n1/proxyutils.py
proxyclient/tools/dump_pmgr.py
proxyclient/tools/pmgr_adt2dt.py
src/proxy.c
src/proxy.h

This PR enables the proxyclient to be used through the physical UART on A7-A11, T2 SoCs.
On A7-A11, the default frequency is too slow for baudrate 1500000, so change the CPU frequency before going into that baud rate. (T2 default frequency is fast enough)
Support the PMU in A7-A10X, which is over I2C, and the PMU in A11, T2, which is over "spmi,gen0" SPMI. In either case, the panic counter does not seem to exist.
Finally, add support for /arm-io/pmgr with 8-bit IDs. Do note that any hypervisor modifications are not tested.

Enable proxyclient operations on A7-A11, T2 SoCs.

---

Makefile
src/kboot.c
src/kboot.h
src/kboot_t6020_compat.c

After discussion with the Linux DT maintainers we agreed to not extend lists with the generic compatibles anymore [1]. The upstream device trees for t602x devices will be the first devices affected by this. Let m1n1 temporarily add these generic compatibles to keep support for t602x devices in downstream projects relying on generic compatibles.
[1]: https://lore.kernel.org/asahi/12ab93b7-1fc2-4ce0-926e-c8141cfe81bf@kernel.org/

kboot: t6020: Add generic compatibles for downstream compatibility

---

.github/workflows/installer.yml

Pack `esp/m1n1/boot.bin` in the artifact so the artifact zip is directly usable as `package` in the installer. Use the date of the m1n1 commit as date component in the artifact name.  
Include the linux tag in the artifact name to identify the included DTBs.
Use `actions/checkout` for the linux and u-boot repository instead of open coding them.

CI: Make the uefi-only artifact usable for the installer

---

.github/workflows/installer.yml

Only runs on tags shall be used to update the package for the uefi-only installer target. Testing on release branches ensures that the workflow runs before a tag is created.
Intended for https://github.com/AsahiLinux/m1n1/tree/releases/1.5.1 and a `v1.5.1` tag to be created on that branch.

CI: uefi-only: Run on tags and `releases/*` branches

---

rust/src/adt.rs
src/adt.h
src/kboot_atc.c

```
-------------------------------------------------------------------------------------------------------------
rust: adt: Add adt property string iterator
This will be used to check all compatible strings in
`adt_is_compatible()`. For now use it to implement ADTNode::compatible()
returning the n-th compatible string on rust side and the C wrapper
function adt_is_compatible_at().
-------------------------------------------------------------------------------------------------------------
kboot_atc: fuses: Check only the first compatible
The t602x atc-phy nodes carry "[atc-phy,t6020, atc-phy,t8112]" as
compatible property. This results in trying to read t8112 fuses on those
machines which fails with SError when the adt_is_compatible() regression
is fixed. …
```

Rust ADT fixes and improvements

---

.github/workflows/build.yml
.github/workflows/installer.yml

Do not explicitily request rustup's stable toolchain as that will not be fully installed when it diverges from the rust install in github's CI runner image.

CI: build/installer: Install aarch64-unknown-none-softfloat target
